Blogs/Controllers/AdController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using Blogs.DAL.Entities;
using Blogs.DAL.Repositories;
using Blogs.Models;
using Blogs.Services;
using Blogs.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Blogs.Controllers
{
    public class AdController : Controller
    {
        private readonly IAdService _adService;
        private readonly UserManager<User> _userManager;
        

        public AdController(IAdService adService, UserManager<User> userManager)
        {
            _adService = adService;
            _userManager = userManager;
            
        }

        public IActionResult Index(AdIndexModel model)
        {
            try
            {
                var recordModels = _adService.GetAllAds(model);
                model.Ads = recordModels;
                

                return View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        [Authorize]
        public IActionResult Create()
        {
            var model = _adService.GetAdCreateModel();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateRecord(AdCreateModel model)
        {
            try
            {
                User currentUser = await _userManager.GetUserAsync(User);

                _adService.CreateAd(model, currentUser.Id);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int recordId)
        {
            var recordModel = _adService.GetAdById(recordId);

            return View(recordModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddComment(AddCommentModel model)
        {
            try
            {
                var currentUser = await _userManager.GetUserAsync(User);
                var commentModel = _adService.AddComment(model, currentUser);

                return Ok(commentModel);
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult Index()
        {
            try
            {
                AdIndexModel model = new AdIndexModel();
                model.UpTime = DateTime.Now;
                model.DateFrom = model.UpTime;
                var recordModels = _adService.GetAllAds(model);
                model.Ads = recordModels;
                return View(model);
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult UpAjax(int recordId)
        {
            try
            {
                var likes = _adService.AddUp(recordId);
                return Ok(likes);
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }
    }
}

Blogs/Views/Ad/Create.cshtml
@model Blogs.Models.AdCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>RecordCreateModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRecord" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contacts" class="control-label"></label>
                <input asp-for="Contacts" class="form-control" />
                <span asp-validation-for="Contacts" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="Model.CategoriesSelect"></select>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Blogs/Views/Ad/Details.cshtml
@model Blogs.Models.AdModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>RecordModel</h4>
    <hr />
    @if (Model.Image != null && Model.Image.Length > 0)
    {
        <img style="width: 50%; height: 50%" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Image))" />
    }
    <br />
    @if (!string.IsNullOrWhiteSpace(Model.ImagePath))
    {
        <img style="width: 50%; height: 50%" src="@Url.Content(Model.ImagePath)" />
    }
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.DatePublished)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.DatePublished)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Author)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Author)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Title)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Title)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Contacts)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Contacts)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Price)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Price)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Content)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Content)
    </dd>
</dl>

    <table id="commentsTable" class="table">
        <tbody>
            @foreach (var item in Model.Comments)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AuthorName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <div><input type="button" id="addComment" class="btn-primary" value="Comment" /></div>
    <div id="commentForm" style="display: none">
        <div><textarea id="commentText" class="form-control"></textarea></div>
        <div><input type="button" id="sendComment" class="btn-primary" value="Send" /></div>
    </div>
    <br />
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts
{
    <script>

        $('#addComment').click(function () {
            $('#commentForm').val('');
            $('#commentForm').show();
            $('#addComment').hide();
        });

        $('#sendComment').click(function () {

            var comment = $('#commentText').val();
            var recordId = '@Model.Id';
            $.ajax({
                url: '@Url.Action("AddComment", "Ad")',
                method: 'POST',
                data: { 'comment': comment, 'recordId': recordId },
                dataType: 'JSON',
                error: function (data) {
                    console.log(data);
                    alert('Error ' + data.status + "\n" + data.responseText);
                },
                success: function (data) {
                    $('#commentForm').hide();
                    $('#addComment').show();
                    var authorCell = "<td>" + data.authorName + "</td>";
                    var createdOnCell = "<td>" + data.createdOn + "</td>";
                    var content = "<td colspan='2'>" + data.content + "</td>";
                    var newRow = "<tr>" + authorCell + createdOnCell + "</tr>" + "<tr>" + content + "</tr>";
                    $('#commentsTable tbody').append(newRow);
                }
            });
        });

    </script>
}

Blogs/Views/Ad/Index.cshtml
@model AdIndexModel

@{
    ViewData["Title"] = "Index";
}
<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Page" value="@Model.Page" />
            <div class="form-group">
                <label asp-for="SearchKey" class="control-label"></label>
                <input asp-for="SearchKey" class="form-control" value="@Model.SearchKey" />
                <span asp-validation-for="SearchKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" value="@Model.Author" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" value="@Model.Category" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceFrom" class="control-label"></label>
                <input asp-for="PriceFrom" class="form-control" value="@Model.PriceFrom" />
                <span asp-validation-for="PriceFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceTo" class="control-label"></label>
                <input asp-for="PriceTo" class="form-control" value="@Model.PriceTo" />
                <span asp-validation-for="PriceTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<table class="table">
    <tbody>
        @foreach (var item in Model.Ads)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DatePublished)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contacts)
                </td>
                <td>
                    <a asp-action="Details" asp-route-recordId="@item.Id">
                        @Html.DisplayFor(modelItem => item.Title)
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ContentPreview)
                </td>
                <td id="likesCount-@item.Id">
                    Кол-во лайков
                    @Html.DisplayFor(modelItem => item.Up)
                </td>
                <td>
                    <input type="button" value="Поднять объявление" onclick="upTime(@item.Id)" />
                </td>
                <td>
                    <input type="button" value="Лайк" onclick="up('@item.Id')" />
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.PagingModel.HasPreviousPage)
{
    @Html.ActionLink("<< Назад", "Index", "Ad",
        new AdIndexModel()
        {
            Author = Model.Author,
            SearchKey = Model.SearchKey,
            DateFrom = Model.UpTime,
            DateTo = Model.DateTo,
            PriceFrom = Model.PriceFrom,
            PriceTo = Model.PriceTo,
            Category = Model.Category,
            Page = Model.Page - 1
        })
}

<b>@Model.Page</b>

@if (Model.PagingModel.HasNextPage)
{
    @Html.ActionLink("Вперед >>", "Index", "Ad",
        new AdIndexModel()
        {
            Author = Model.Author,
            SearchKey = Model.SearchKey,
            DateFrom = Model.UpTime,
            DateTo = Model.DateTo,
            PriceFrom = Model.PriceFrom,
            PriceTo = Model.PriceTo,
            Category = Model.Category,
            Page = Model.Page + 1
        })
}
@section Scripts
{
    <script>

        function up(recordId) {
            $.ajax({
                url: '@Url.Action("UpAjax", "Ad")',
                method: 'POST',
                data: { 'recordId': recordId },
                error: function(data) {
                    console.log(data);
                    alert('Error ' + data.status + "\n" + data.responseText);
                },
                success: function(data) {
                    $('#likesCount-' + recordId).html(data);
                }
            });
        }
    </script>
}
<script>
        function upTime(recordId) {
            $.ajax({
                url: '@Url.Action("Index", "Ad")',
                method: 'POST',
                data: { 'recordId': recordId },
                error: function(data) {
                    console.log(data);
                    alert('Error ' + data.status + "\n" + data.responseText);
                },
                success: function(data) {
                    $('Обновлено-' + recordId).html(data);
                }
            });
        }

</script>